analytics: {}
author:
  email: ''
  name: ''
  url: ''
color:
  brandColors:
    - '#000000'
    - '#f6fbf5'
    - '#0054f4'
    - '#f90100'
    - '#38fa6a'
  brandStrength: 0.9
  lightness: 0.3123
  rhythmicContrast: 0.9
  saturation: 0.625
content_rating:
  adult: false
cta: {}
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b86b8ba0-78db-4d3a-86c7-c8de521a22ce.ico
layout_spectrum: 0.852194599667564
name: bergie@c-base
opengraph:
  appId: ''
  image: >-
    https://imgflo.herokuapp.com/graph/vahj1ThiexotieMo/8015627eaac33f8f08c796cf78bfadc1/gradientmap.jpg?stop1=0.1&stop2=0.3&stop3=0.5&stop4=0.7&stop5=0.9&color1=%23161F14&color2=%232C3D29&color3=%23587A52&color4=%236AFB8E&color5=%23CDFED9&srgb=True&input=https%3A%2F%2Fthe-grid-user-content.s3-us-west-2.amazonaws.com%2Fbf61a14a-3ff2-4a8a-8b32-11f57be2cb96.jpg&width=948&height=1262
  type: website
title: ''
typography_spectrum: 0.26755
github: true
